import dotenv from 'dotenv';
dotenv.config();

export const config = {
  port: parseInt(process.env.PORT || '3001'),
  nodeEnv: process.env.NODE_ENV || 'development',
  concurrentQueries: parseInt(process.env.CONCURRENT_QUERIES || '20'),
  maxPagesPerQuery: parseInt(process.env.MAX_PAGES_PER_QUERY || '20'),
  requestDelayMs: parseInt(process.env.REQUEST_DELAY_MS || '500'),
  maxRetries: parseInt(process.env.MAX_RETRIES || '3'),
  cacheTtlHours: parseInt(process.env.CACHE_TTL_HOURS || '24'),
  dataDir: './data',
};

export const searchKeywords = {
  guestPost: [
    'write for us',
    'guest post',
    'submit article',
/*    'contribute',
    'guest author',
    'submit guest post',
    'become a contributor',
    'guest posting guidelines',
    'guest blog',
    'accepting guest posts',*/
  ],
  linkInsertion: [
/*    'link insertion',
    'sponsored post',
    'paid post',
    'advertise with us',
    'advertising opportunities',
    'sponsored content',
    'paid links',
    'niche edit',*/
  ],
};

export const niches = [
  { id: 'technology', name: 'Technology', keywords: ['tech', 'software', 'IT', 'digital'] },
  { id: 'marketing', name: 'Marketing', keywords: ['marketing', 'SEO', 'digital marketing', 'content'] },
  { id: 'business', name: 'Business', keywords: ['business', 'startup', 'entrepreneur', 'finance'] },
  { id: 'health', name: 'Health & Wellness', keywords: ['health', 'fitness', 'wellness', 'nutrition'] },
  { id: 'travel', name: 'Travel', keywords: ['travel', 'tourism', 'vacation', 'destinations'] },
  { id: 'lifestyle', name: 'Lifestyle', keywords: ['lifestyle', 'home', 'fashion', 'beauty'] },
  { id: 'education', name: 'Education', keywords: ['education', 'learning', 'courses', 'training'] },
  { id: 'food', name: 'Food & Cooking', keywords: ['food', 'recipes', 'cooking', 'cuisine'] },
  { id: 'finance', name: 'Finance', keywords: ['finance', 'investing', 'money', 'personal finance'] },
  { id: 'realestate', name: 'Real Estate', keywords: ['real estate', 'property', 'housing', 'homes'] },
  { id: 'automotive', name: 'Automotive', keywords: ['automotive', 'cars', 'vehicles', 'auto'] },
  { id: 'sports', name: 'Sports', keywords: ['sports', 'fitness', 'athletics', 'outdoor'] },
];

export const countries = [
  // North America
  { code: 'us', name: 'United States', tld: '.com' },
  { code: 'ca', name: 'Canada', tld: '.ca' },
  { code: 'mx', name: 'Mexico', tld: '.mx' },
  
  // Central America & Caribbean
  { code: 'gt', name: 'Guatemala', tld: '.gt' },
  { code: 'hn', name: 'Honduras', tld: '.hn' },
  { code: 'sv', name: 'El Salvador', tld: '.sv' },
  { code: 'ni', name: 'Nicaragua', tld: '.ni' },
  { code: 'cr', name: 'Costa Rica', tld: '.cr' },
  { code: 'pa', name: 'Panama', tld: '.pa' },
  { code: 'bz', name: 'Belize', tld: '.bz' },
  { code: 'jm', name: 'Jamaica', tld: '.jm' },
  { code: 'tt', name: 'Trinidad and Tobago', tld: '.tt' },
  { code: 'bs', name: 'Bahamas', tld: '.bs' },
  { code: 'bb', name: 'Barbados', tld: '.bb' },
  { code: 'do', name: 'Dominican Republic', tld: '.do' },
  { code: 'cu', name: 'Cuba', tld: '.cu' },
  { code: 'ht', name: 'Haiti', tld: '.ht' },
  
  // South America
  { code: 'br', name: 'Brazil', tld: '.com.br' },
  { code: 'ar', name: 'Argentina', tld: '.ar' },
  { code: 'cl', name: 'Chile', tld: '.cl' },
  { code: 'co', name: 'Colombia', tld: '.co' },
  { code: 'pe', name: 'Peru', tld: '.pe' },
  { code: 've', name: 'Venezuela', tld: '.ve' },
  { code: 'ec', name: 'Ecuador', tld: '.ec' },
  { code: 'bo', name: 'Bolivia', tld: '.bo' },
  { code: 'py', name: 'Paraguay', tld: '.py' },
  { code: 'uy', name: 'Uruguay', tld: '.uy' },
  { code: 'gy', name: 'Guyana', tld: '.gy' },
  { code: 'sr', name: 'Suriname', tld: '.sr' },
  
  // Western Europe
  { code: 'gb', name: 'United Kingdom', tld: '.co.uk' },
  { code: 'ie', name: 'Ireland', tld: '.ie' },
  { code: 'fr', name: 'France', tld: '.fr' },
  { code: 'de', name: 'Germany', tld: '.de' },
  { code: 'es', name: 'Spain', tld: '.es' },
  { code: 'pt', name: 'Portugal', tld: '.pt' },
  { code: 'it', name: 'Italy', tld: '.it' },
  { code: 'nl', name: 'Netherlands', tld: '.nl' },
  { code: 'be', name: 'Belgium', tld: '.be' },
  { code: 'ch', name: 'Switzerland', tld: '.ch' },
  { code: 'at', name: 'Austria', tld: '.at' },
  { code: 'lu', name: 'Luxembourg', tld: '.lu' },
  { code: 'mc', name: 'Monaco', tld: '.mc' },
  
  // Northern Europe
  { code: 'se', name: 'Sweden', tld: '.se' },
  { code: 'no', name: 'Norway', tld: '.no' },
  { code: 'dk', name: 'Denmark', tld: '.dk' },
  { code: 'fi', name: 'Finland', tld: '.fi' },
  { code: 'is', name: 'Iceland', tld: '.is' },
  
  // Eastern Europe
  { code: 'pl', name: 'Poland', tld: '.pl' },
  { code: 'cz', name: 'Czech Republic', tld: '.cz' },
  { code: 'sk', name: 'Slovakia', tld: '.sk' },
  { code: 'hu', name: 'Hungary', tld: '.hu' },
  { code: 'ro', name: 'Romania', tld: '.ro' },
  { code: 'bg', name: 'Bulgaria', tld: '.bg' },
  { code: 'ua', name: 'Ukraine', tld: '.ua' },
  { code: 'by', name: 'Belarus', tld: '.by' },
  { code: 'md', name: 'Moldova', tld: '.md' },
  { code: 'ru', name: 'Russia', tld: '.ru' },
  { code: 'ee', name: 'Estonia', tld: '.ee' },
  { code: 'lv', name: 'Latvia', tld: '.lv' },
  { code: 'lt', name: 'Lithuania', tld: '.lt' },
  
  // Southern Europe
  { code: 'gr', name: 'Greece', tld: '.gr' },
  { code: 'cy', name: 'Cyprus', tld: '.cy' },
  { code: 'mt', name: 'Malta', tld: '.mt' },
  { code: 'hr', name: 'Croatia', tld: '.hr' },
  { code: 'si', name: 'Slovenia', tld: '.si' },
  { code: 'rs', name: 'Serbia', tld: '.rs' },
  { code: 'ba', name: 'Bosnia and Herzegovina', tld: '.ba' },
  { code: 'me', name: 'Montenegro', tld: '.me' },
  { code: 'mk', name: 'North Macedonia', tld: '.mk' },
  { code: 'al', name: 'Albania', tld: '.al' },
  
  // Middle East
  { code: 'ae', name: 'United Arab Emirates', tld: '.ae' },
  { code: 'sa', name: 'Saudi Arabia', tld: '.sa' },
  { code: 'il', name: 'Israel', tld: '.il' },
  { code: 'tr', name: 'Turkey', tld: '.tr' },
  { code: 'ir', name: 'Iran', tld: '.ir' },
  { code: 'iq', name: 'Iraq', tld: '.iq' },
  { code: 'jo', name: 'Jordan', tld: '.jo' },
  { code: 'lb', name: 'Lebanon', tld: '.lb' },
  { code: 'sy', name: 'Syria', tld: '.sy' },
  { code: 'ye', name: 'Yemen', tld: '.ye' },
  { code: 'om', name: 'Oman', tld: '.om' },
  { code: 'kw', name: 'Kuwait', tld: '.kw' },
  { code: 'qa', name: 'Qatar', tld: '.qa' },
  { code: 'bh', name: 'Bahrain', tld: '.bh' },
  
  // Asia-Pacific
  { code: 'cn', name: 'China', tld: '.cn' },
  { code: 'jp', name: 'Japan', tld: '.jp' },
  { code: 'kr', name: 'South Korea', tld: '.kr' },
  { code: 'in', name: 'India', tld: '.in' },
  { code: 'pk', name: 'Pakistan', tld: '.pk' },
  { code: 'bd', name: 'Bangladesh', tld: '.bd' },
  { code: 'lk', name: 'Sri Lanka', tld: '.lk' },
  { code: 'np', name: 'Nepal', tld: '.np' },
  { code: 'mm', name: 'Myanmar', tld: '.mm' },
  { code: 'th', name: 'Thailand', tld: '.th' },
  { code: 'vn', name: 'Vietnam', tld: '.vn' },
  { code: 'ph', name: 'Philippines', tld: '.ph' },
  { code: 'id', name: 'Indonesia', tld: '.id' },
  { code: 'my', name: 'Malaysia', tld: '.my' },
  { code: 'sg', name: 'Singapore', tld: '.sg' },
  { code: 'bn', name: 'Brunei', tld: '.bn' },
  { code: 'kh', name: 'Cambodia', tld: '.kh' },
  { code: 'la', name: 'Laos', tld: '.la' },
  { code: 'mn', name: 'Mongolia', tld: '.mn' },
  { code: 'kz', name: 'Kazakhstan', tld: '.kz' },
  { code: 'uz', name: 'Uzbekistan', tld: '.uz' },
  { code: 'tm', name: 'Turkmenistan', tld: '.tm' },
  { code: 'kg', name: 'Kyrgyzstan', tld: '.kg' },
  { code: 'tj', name: 'Tajikistan', tld: '.tj' },
  { code: 'af', name: 'Afghanistan', tld: '.af' },
  
  // Oceania
  { code: 'au', name: 'Australia', tld: '.com.au' },
  { code: 'nz', name: 'New Zealand', tld: '.nz' },
  { code: 'fj', name: 'Fiji', tld: '.fj' },
  { code: 'pg', name: 'Papua New Guinea', tld: '.pg' },
  { code: 'sb', name: 'Solomon Islands', tld: '.sb' },
  { code: 'vu', name: 'Vanuatu', tld: '.vu' },
  { code: 'ws', name: 'Samoa', tld: '.ws' },
  { code: 'to', name: 'Tonga', tld: '.to' },
  
  // Africa - North
  { code: 'eg', name: 'Egypt', tld: '.eg' },
  { code: 'ly', name: 'Libya', tld: '.ly' },
  { code: 'tn', name: 'Tunisia', tld: '.tn' },
  { code: 'dz', name: 'Algeria', tld: '.dz' },
  { code: 'ma', name: 'Morocco', tld: '.ma' },
  { code: 'sd', name: 'Sudan', tld: '.sd' },
  
  // Africa - West
  { code: 'ng', name: 'Nigeria', tld: '.ng' },
  { code: 'gh', name: 'Ghana', tld: '.gh' },
  { code: 'sn', name: 'Senegal', tld: '.sn' },
  { code: 'ci', name: 'Ivory Coast', tld: '.ci' },
  { code: 'ml', name: 'Mali', tld: '.ml' },
  { code: 'bf', name: 'Burkina Faso', tld: '.bf' },
  { code: 'ne', name: 'Niger', tld: '.ne' },
  { code: 'tg', name: 'Togo', tld: '.tg' },
  { code: 'bj', name: 'Benin', tld: '.bj' },
  { code: 'gm', name: 'Gambia', tld: '.gm' },
  { code: 'gw', name: 'Guinea-Bissau', tld: '.gw' },
  { code: 'gn', name: 'Guinea', tld: '.gn' },
  { code: 'sl', name: 'Sierra Leone', tld: '.sl' },
  { code: 'lr', name: 'Liberia', tld: '.lr' },
  
  // Africa - East
  { code: 'ke', name: 'Kenya', tld: '.ke' },
  { code: 'tz', name: 'Tanzania', tld: '.tz' },
  { code: 'ug', name: 'Uganda', tld: '.ug' },
  { code: 'et', name: 'Ethiopia', tld: '.et' },
  { code: 'so', name: 'Somalia', tld: '.so' },
  { code: 'rw', name: 'Rwanda', tld: '.rw' },
  { code: 'bi', name: 'Burundi', tld: '.bi' },
  { code: 'dj', name: 'Djibouti', tld: '.dj' },
  { code: 'er', name: 'Eritrea', tld: '.er' },
  
  // Africa - Southern
  { code: 'za', name: 'South Africa', tld: '.co.za' },
  { code: 'zw', name: 'Zimbabwe', tld: '.zw' },
  { code: 'zm', name: 'Zambia', tld: '.zm' },
  { code: 'mw', name: 'Malawi', tld: '.mw' },
  { code: 'mz', name: 'Mozambique', tld: '.mz' },
  { code: 'bw', name: 'Botswana', tld: '.bw' },
  { code: 'na', name: 'Namibia', tld: '.na' },
  { code: 'sz', name: 'Eswatini', tld: '.sz' },
  { code: 'ls', name: 'Lesotho', tld: '.ls' },
  { code: 'mg', name: 'Madagascar', tld: '.mg' },
  { code: 'mu', name: 'Mauritius', tld: '.mu' },
  { code: 'sc', name: 'Seychelles', tld: '.sc' },
  { code: 'km', name: 'Comoros', tld: '.km' },
  
  // Africa - Central
  { code: 'cm', name: 'Cameroon', tld: '.cm' },
  { code: 'cf', name: 'Central African Republic', tld: '.cf' },
  { code: 'td', name: 'Chad', tld: '.td' },
  { code: 'cg', name: 'Republic of the Congo', tld: '.cg' },
  { code: 'cd', name: 'Democratic Republic of the Congo', tld: '.cd' },
  { code: 'ga', name: 'Gabon', tld: '.ga' },
  { code: 'gq', name: 'Equatorial Guinea', tld: '.gq' },
  { code: 'st', name: 'São Tomé and Príncipe', tld: '.st' },
  { code: 'ao', name: 'Angola', tld: '.ao' },
];